Intro
spinlock99/invaders-from-space pull request #25
Opened 2019-01-19 23:16 UTC by Johnnycus

Please create "intro" branch so I can open pull request pointing to that

2019-01-24 23:07 UTC, spinlock99 requested changes
This is awesome!

I had a few comments on linting, etc... but overall I'm impressed with the code quality.

2019-01-24 23:07 UTC, spinlock99 commented on src/reducer.js
> +  introSlide: 0
Should this be `currentSlide` instead of `introSlide`?

2019-01-24 23:11 UTC, spinlock99 commented on src/index.ejs
> +
Same as above. Please keep changes as small as possible.

Can the `font-family` be moved into the component or put on `#container`?

2019-01-25 00:21 UTC, Johnnycus commented on src/index.ejs
> +  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0" />
My bad, haven't checked the settings of my Prettier config. Will fix it!

2019-02-05 19:13 UTC, merged